"""chat_conversacional_models

Revision ID: 9b15c404aa46
Revises: 026d2f56bfbe
Create Date: 2026-05-05 03:42:00.878162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9b15c404aa46'
down_revision: Union[str, None] = '026d2f56bfbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessoes_chat',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('usuario_id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=50), nullable=True),
    sa.Column('titulo', sa.String(length=200), nullable=True),
    sa.Column('contexto_json', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('ativa', 'concluida', 'arquivada', name='status_sessao_chat_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs_agente.job_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessoes_chat_job_id'), 'sessoes_chat', ['job_id'], unique=False)
    
    op.create_table('mensagens_chat',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sessao_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.Enum('user', 'assistant', 'system', 'tool', name='role_mensagem_chat_enum'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tool_calls', sa.JSON(), nullable=True),
    sa.Column('tool_call_id', sa.String(length=100), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sessao_id'], ['sessoes_chat.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mensagens_chat_sessao_id'), 'mensagens_chat', ['sessao_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mensagens_chat_sessao_id'), table_name='mensagens_chat')
    op.drop_table('mensagens_chat')
    op.drop_index(op.f('ix_sessoes_chat_job_id'), table_name='sessoes_chat')
    op.drop_table('sessoes_chat')
    # ### end Alembic commands ###
